version: "3.0"

services:
  api:
    build:
      context: .
    container_name: api
    command: >
      sh -c "python main.py"
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    env_file:
      - .env
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
